{{- $vm := .Values.VirtualMachine -}}
{{- range $i, $e := until (int $vm.count) }}
{{- $vmName := printf "%s-%02d" $vm.baseName $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: fakefish-{{ $vmName }}-{{ $.Release.Name }}
  namespace: {{ $.Release.Name }}
  labels:
{{- range $key, $value := $.Values.common.metadata.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
  annotations:
{{- if $.Values.service.metalLBEnabled }}
    metallb.universe.tf/ip-allocated-from-pool: {{ $.Values.service.IPAddressPool }}
{{- end }}
spec:
  type: {{ if $.Values.service.metalLBEnabled }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: fakefish-{{ $vmName }}-{{ $.Release.Name }}
{{- if $.Values.service.metalLBEnabled }}
  loadBalancerIP: {{ index $.Values.service.loadBalancerIPs $vmName }}
{{- end }}
{{- end }}
